### ISSUE TITLE
Provide schemas to help design the database and JSON schemas

### ISSUE THREAD

**Issue by andrewyatz** [Ensembl/chanaka-gsoc-2017#1]
In order to design good database and JSON data structures we need to provide the original Ensembl data schemas. We will provide the following

- [x] The link to the core ER diagram
- [x] SQL schema for core
- [x] The connection details to connect to the public Ensembl MySQL servers
- [x] An example of the web data hash and description of keys/meaning
- [x] A trackDb example and explanation of the keys being used

In addition we will highlight the areas of the core scheme of interest. This will form the first use-case of the project

**Comment by sanjay-boddu** [comment]
1.  The link to the core ER diagram
Here it is: http://www.ensembl.org/info/docs/api/core/core_schema.html
See the ER diagrams involving analysis and analysis_description tables.

1. SQL schema for core
https://github.com/Ensembl/ensembl/blob/release/88/sql/table.sql

1. The connection details to connect to the public Ensembl MySQL servers
Host: ensembldb.ensembl.org
User: anonymous
Port: 3306

1.  An example of the web data hash and description of keys/meaning
https://www.ebi.ac.uk/seqdb/confluence/display/ENSWEB/Control+of+web+display+using+analysis_description+table

1.  A trackDb example and explanation of the keys being used
https://genome.ucsc.edu/goldenpath/help/trackDb/trackDbHub.html

**Comment by sanjay-boddu** [comment]
4. Sorry, you will need EBI account to access that page. Here is the PDF version of it.
[Control of web display using analysis_description table - Ensembl Web - EMBL-EBI Confluence.pdf](https://github.com/Ensembl/chanaka-gsoc-2017/files/995722/Control.of.web.display.using.analysis_description.table.-.Ensembl.Web.-.EMBL-EBI.Confluence.pdf)

**Comment by chanakaDe** [comment]
Thanks for all the information. I will ask if I have anything unclear :+1:

**Comment by andrewyatz** [comment]
Closing the issue now as this looks like it is done
