### ISSUE TITLE
Loading tracks into the database from Ensembl

### ISSUE THREAD

**Issue by andrewyatz** [Ensembl/chanaka-gsoc-2017#10]
Run this bash command to log into the server:

```bash
$ mysql -hensembldb.ensembl.org -uanonymous homo_sapiens_core_89_38
```

This schema's species is `homo_sapiens` (`location_species`), its schema type is `core` (`location_dbtype`) and the object type we are retrieving here is `gene` (`location_object_type`).

Then run this SQL and find all displayable tracks in an Ensembl core schema for genes e.g.

```SQL
select a.analysis_id, logic_name, ad.description, ad.display_label, ad.web_data
FROM (
	select distinct(analysis_id) as analysis_id from gene 
) as a 
join analysis on (a.analysis_id = analysis.analysis_id) 
join analysis_description as ad on (analysis.analysis_id = ad.analysis_id)
where ad.displayable = 1;
```

- logic_name is the same as `location_logic_name` and should be linked as such
- description is the same as track description
- web_data is a Perl formatted data structure. Simple regex of `=>` to `:` should mean you can use JSON deserialisers to get back to a data structure

Loop through the web data fields and look for where the field `key` is repeated. These entries should be combined into a single track.

**Comment by andrewyatz** [comment]
In web data we have:

- `multi_name` this is long_name (only available when key is set)
- `caption` can be used for short_name as well
- `key` used to group multiple analysis entries together

**Comment by andrewyatz** [comment]
Some fields of data we should query for to fill in is for genome:

```SQL
select * from meta where meta_key IN ('assembly.default', 'species.production_name', 'species.strain_collection', 'species.division', 'schema_type', 'schema_version');
```

Example output from the latest release of Ensembl human database

```
1	NULL	schema_type	core
2	NULL	schema_version	89
22	1	assembly.default	GRCh38
2910	1	species.production_name	homo_sapiens
2909	1	species.division	Ensembl
```

Key mapping is

- assembly.default is genome_assembly
- species.production_name is genome_species
- species.division is release_division
- schema_version is release_version
- species.strain_collection existing is the same as genome_strain

**Comment by andrewyatz** [comment]
track_type depends on the table you join to in the original query. In this case it is gene.

**Comment by nicklangridge** [comment]
The work for this issue is complete - pending review of database dump

**Comment by andrewyatz** [comment]
Pending the re-write of laravel persistence layer in Java and using the same JPA framework as the Elastic loader

**Comment by andrewyatz** [comment]
This has been implemented in https://github.com/chanakaDe/ensembl-db-convert
