### ISSUE TITLE
Working REST API on top of Elastic search

### ISSUE THREAD

**Issue by andrewyatz** [Ensembl/chanaka-gsoc-2017#13]
As defined in #6

**Comment by chanakaDe** [comment]
Here's the development version of the REST API.
Some important files here.

This is my Track model.
https://github.com/chanakaDe/ensembl-elastic-rest/blob/master/src/main/java/com/chanaka/book/model/Track.java

And also here I implemented the Track Controller. This is the RESTful layer of the application.
https://github.com/chanakaDe/ensembl-elastic-rest/blob/master/src/main/java/com/chanaka/book/controller/TrackController.java
As for now, only get all tracks and find by id is there. Working on other functions at this moment.

And following are Track Service, ServiceImpl and also Elastic Track Repository.
https://github.com/chanakaDe/ensembl-elastic-rest/blob/master/src/main/java/com/chanaka/book/service/TrackService.java

https://github.com/chanakaDe/ensembl-elastic-rest/blob/master/src/main/java/com/chanaka/book/service/TrackServiceImpl.java

https://github.com/chanakaDe/ensembl-elastic-rest/blob/master/src/main/java/com/chanaka/book/repository/TrackRepository.java

**Comment by andrewyatz** [comment]
In progress see #18

**Comment by andrewyatz** [comment]
Working pending pagination

**Comment by andrewyatz** [comment]
We will not do pagination. Pending final commits from Heroku version due by tomorrow

**Comment by chanakaDe** [comment]
All the latest files and commits have updated to the git repository and also to Heroku
