### ISSUE TITLE
Deployment to Heroku

### ISSUE THREAD

**Issue by andrewyatz** [Ensembl/chanaka-gsoc-2017#16]
- [x] Load application into Heroku
- [x] Use a Bonsai Elasticsearch instance to host the test data (https://elements.heroku.com/addons/bonsai)

**Comment by andrewyatz** [comment]
Still need to use the components in heroku and will document this work tomorrow

**Comment by chanakaDe** [comment]
Couldn't deploy Heroku based mysql and elastic search because free account is not allowed to add those add-ons. So need to add credit card info and fix this in future.
