### ISSUE TITLE
Documentation of all components

### ISSUE THREAD

**Issue by andrewyatz** [Ensembl/chanaka-gsoc-2017#19]
- [x] Web application front-end design and adding new pages
- [x] Web application deployment; how to run
- [x] REST API application
- [x] Ensembl MySQL to track db MySQL import documentation install and build
- [x] Ensembl MySQL to track db MySQL import documentation; how to run
- [x] Track db MySQL to ElasticSearch import documentation install and build
- [x] Track db MySQL to ElasticSearch import documentation; how to run

Put these with the projects as a README.md on each GitHub repo. I suggest the following structure for this.

```
# NAME OF PROJECT
Short description

#SYNPOSIS
  `How to run the command`

# DESCRIPTION
Bigger description

# INSTALL
How to install

# RUN
How to run
```

**Comment by andrewyatz** [comment]
See #20 for more templates

**Comment by chanakaDe** [comment]
All the documentation sections are done. available on each project component separately
