### ISSUE TITLE
Provide an example of the current track configuration interface 

### ISSUE THREAD

**Issue by andrewyatz** [Ensembl/chanaka-gsoc-2017#3]
Take a screenshot and annotate the current track configuration interface. We should point out

- The track name
- The description
- Any short descriptions used
- The nested facets
- Renderer configuration
- Any other options

**Comment by nicklangridge** [comment]
To see the interface in action browse to http://www.ensembl.org/Homo_sapiens/Location/View?r=17:63973115-64437414 then click the button labelled "Configure this page" in the left-hand-menu. Screenshots to follow...

**Comment by nicklangridge** [comment]
An example of the track configuration interface in Ensembl:
![track-selection](https://cloud.githubusercontent.com/assets/693304/26006514/98e45286-3734-11e7-85e6-5b383bcbbacb.png)

An example where a track hub has been loaded:
![track-selection-hub](https://cloud.githubusercontent.com/assets/693304/26006517/9b6351ec-3734-11e7-90cc-6019ddf519fe.png)

See corresponding hub files:
http://apprisws.bioinfo.cnio.es/trackHub/hub.txt
http://apprisws.bioinfo.cnio.es/trackHub/trackDb.hg38.txt

**Comment by chanakaDe** [comment]
About "An example where a track hub has been loaded:"
I can't see a link like "Principal Splice Isoforms....." below the search results.
Can you please explain me how I get there ? 
![screenshot from 2017-05-18 17-27-19](https://cloud.githubusercontent.com/assets/7803591/26201167/4e16efba-3bef-11e7-9af4-20d5cc98ea70.png)

**Comment by nicklangridge** [comment]
First you have to find and attach the Principal Splice Isoforms track hub.
From the position in your screenshot, do the following:

1. click the 'Personal Data' tab
2. click the 'Search for public track hubs' link
3. type 'principal isoforms' in the 'Text search' box and click 'Search'
4. click 'Attach this hub' for the Principal Isoforms search result
5. click 'configure your hub'

You should now see the Principal Splice Isoforms menu in your configuration screen.

**Comment by andrewyatz** [comment]
Is this okay to close?
