### ISSUE TITLE
Define what will be delivered in each of the coding periods

### ISSUE THREAD

**Issue by andrewyatz** [Ensembl/chanaka-gsoc-2017#6]
Ensure we define what we will produce for each coding period. On the last telco we agreed month 3 would be to produce the GUI interface. We will make sure this is discussed at the next telco

**Comment by nicklangridge** [comment]
On the second call we briefly discussed deliverables for each stage, we thought they should be something along the following lines (@chanakaDe please comment if you see things differently):

Month 1
- new database and JSON schema
- scripts to populate the database and generate JSON documents for Elastic search

Month 2
- REST endpoint definition
- working REST API on top of Elastic search

Month 3
- functional search GUI

**Comment by andrewyatz** [comment]
New issues have been raised and assigned to the 1, 2 and 3 milestone months
