### ISSUE TITLE
Define the structure and keys of JSON Schema 

### ISSUE THREAD

**Issue by chanakaDe** [Ensembl/chanaka-gsoc-2017#8]
We have to define all the fields [keys and values] which we are going to use in the JSON Schema. 
And also the new structure of the data.

**Comment by andrewyatz** [comment]
I have started to work on this here

https://github.com/Ensembl/chanaka-gsoc-2017/blob/master/schemas/json_schema.md

**Comment by chanakaDe** [comment]
It looks so great :+1:  Please continue .

**Comment by chanakaDe** [comment]
Is there anything new to add in to the "The Schema" and "Keys and meaning" sections ?

**Comment by sanjay-boddu** [comment]
Hi Chanaka,

Yes, we have few more bits to add to it.
We will finalise them soon(may be by the end of today or tomorrow) and update the schema accordingly.

Thanks,
Sanjay

**Comment by andrewyatz** [comment]
Hi. @sanjay-eg and I have edited the above document. Sanjay will do another pass over this before we close the issue but we feel this is fairly complete.

**Comment by chanakaDe** [comment]
@andrewyatz @sanjay-eg Thanks guys. Now we have a great schema to follow and work on :+1: 
Keys and Definitions section helps a lot.....
